package com.demo_soap_api.openlegacy.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;


/**
 * OpenApi configuration
 */
@Configuration
public class DemoSoapApiOpenApiConfiguration {

    /**
     * Configures a specification that will be generated by the SpringDoc.
     * 
     * @return a pre-configured instance of the OpenAPI model.
     */
    @Bean
    public OpenAPI openApiConfiguration() {
        return new OpenAPI()
                .info(new Info()
                        .title("demo-soap-api")
                        .description("demo-soap-api API")
                        .version("0.1"));
    }
}

